on: push

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Original
        run: echo $MY_VAR 
        env:
          MY_VAR: ${{ secrets.MY_SECRET }}
      - name: Python Shell
        run: |
          import os
          print(len(os.getenv('MY_VAR')))
        shell: python
        env:
          MY_VAR: ${{ secrets.MY_SECRET }}
